FROM centos:7
RUN yum clean all && \
    yum update -y

RUN yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
    rpm --import https://download.docker.com/linux/centos/gpg && \
    yum install -y docker-client

COPY test_nginx_log.py /test_nginx_log.py
